import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { GradientBackground } from "@/components/GradientBackground";
import Footer from "@/components/shared/Footer";
import SmoothScrolling from "@/components/SmoothScrolling";
import Navbar from "@/components/shared/Navbar";
import { CartProvider } from "@/contexts/CartContext";
import CartDrawer from "@/components/CartDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-hind",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${hindSiliguri.className}`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Navbar />
          <GradientBackground />

          <SmoothScrolling>
            <main className="relative z-0">{children}</main>
          </SmoothScrolling>
          <Footer />
          <CartDrawer />
        </CartProvider>
      </body>
    </html>
  );
}
